window.keyboard = [
	{"character": "a", "num": 65},
	{"character": "b", "num": 66},
	{"character": "c", "num": 67},
	{"character": "d", "num": 68},
	{"character": "e", "num": 69},
	{"character": "f", "num": 70},
	{"character": "g", "num": 71},
	{"character": "h", "num": 72},
	{"character": "i", "num": 73},
	{"character": "j", "num": 74},
	{"character": "k", "num": 75},
	{"character": "l", "num": 76},
	{"character": "m", "num": 77},
	{"character": "n", "num": 78},
	{"character": "o", "num": 79},
	{"character": "p", "num": 80},
	{"character": "q", "num": 81},
	{"character": "r", "num": 82},
	{"character": "s", "num": 83},
	{"character": "t", "num": 84},
	{"character": "u", "num": 85},
	{"character": "v", "num": 86},
	{"character": "w", "num": 87},
	{"character": "x", "num": 88},
	{"character": "y", "num": 89},
	{"character": "z", "num": 90},
	{"character": " ", "num": 32},
	{"character": "backspace", "num": 8}
];